### ISSUE TITLE
Enable failure - Invalid syntax error `match property_name:`

### ISSUE THREAD

**Issue by OHsit** [Roblox/roblox-blender-plugin#15]
Trying to enable a plugin but an error is  appears
![Przechwytywanie](https://github.com/Roblox/roblox-blender-plugin/assets/79926004/d32365c4-7116-45e5-a3db-c763c15d1806)

**Comment by Nightriff** [comment]
This plugin only works on Blender version 3.2 or higher, which uses a later version of python that supports `match` syntax. Please update your Blender version to at least 3.2 and try again!

**Comment by snakeboybenrich** [comment]
hi im trying to get the plugin on blender but all i get when it open up on roblox is Internal client error.
No module named 'pyjwt_key_fetcher' can you help me please

**Comment by Nightriff** [comment]
> hi im trying to get the plugin on blender but all i get when it open up on roblox is Internal client error. No module named 'pyjwt_key_fetcher' can you help me please

Please add your comment to this other more relevant issue, and follow the debugging steps I added as a reply: https://github.com/Roblox/roblox-blender-plugin/issues/14
