### ISSUE TITLE
Internal client error. The token is not yet valid (iat)

### ISSUE THREAD

**Issue by crecerhecer** [Roblox/roblox-blender-plugin#19]
after giving acces and redirecting to blender this happens
![Screenshot_270](https://github.com/Roblox/roblox-blender-plugin/assets/49832816/a07247a3-414d-49a6-98c8-f9b4d909e76d)

**Comment by crecerhecer** [comment]
![Screenshot_272](https://github.com/Roblox/roblox-blender-plugin/assets/49832816/23779720-17e7-4dae-a426-04d3fd4e0fdb)
fix is easy, u need give access only to your account, and it will be ok, after that u can un-login in blender and login again, now u can give access to account and all groups u can

**Comment by Nightriff** [comment]
I suspect what you give access to does not affect this specific error, it was probably just the process of trying again that made it go through. This is a similar report to this issue: https://github.com/Roblox/roblox-blender-plugin/issues/17
