### ISSUE TITLE
Install failure - Invalid syntax error `match property_name:`

### ISSUE THREAD

**Issue by MKTO46** [Roblox/roblox-blender-plugin#21]
I keep getting this error message every time I try to install the plugin what do I do?
![Screenshot 2023-10-11 183650](https://github.com/Roblox/roblox-blender-plugin/assets/72702490/5d65410e-5818-479c-9229-f79a9927746a)

**Comment by itsFrank** [comment]
The plugin requires Blender version 3.2 or newer, see the [installation instructions](https://github.com/Roblox/roblox-blender-plugin#install-new-version) on the README

**Comment by Nightriff** [comment]
Same issue as https://github.com/Roblox/roblox-blender-plugin/issues/15
