### ISSUE TITLE
Bug. Can't Upload From Blender

### ISSUE THREAD

**Issue by EngyneMac** [Roblox/roblox-blender-plugin#32]
bug, idk how to put label
 
 I think this bug might be related to 4.0.0. After the update my add-on was gone so i had to reinstall it this error showed up.
 
 Python: Traceback (most recent call last):
  File "C:\Users\40787\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\roblox-blender-plugin\lib\get_selected_objects.py", line 66, in get_selected_objects
    for selected_object in context.selected_ids:
AttributeError: 'Context' object has no attribute 'selected_ids'. Did you mean: 'selected_bones'?

 
![image](https://github.com/Roblox/roblox-blender-plugin/assets/150859697/15c7c782-6acd-4854-ac42-19e58b0a4969)

**Comment by heliawins** [comment]
yea i see now i also have the same problem i need help with this

**Comment by heliawins** [comment]
hi never mind i fixed it go to this location in files C:\Users\neels\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\roblox-blender-plugin\lib and go into the folder get_selected_objects.py and open it with notepad or anything that's like notepad and look for this for selected_object in context.selected_ids and change the word ids to objects and save it then restart blender. if wanna know how i fixed this problem i asked chat gpt for help its an ai and it worked hopefully this don't get deleted

**Comment by EngyneMac** [comment]
It worked. Thanks!

**Comment by Nightriff** [comment]
This issue was fixed in v1.0.2, thanks for reporting!
Latest release here: https://github.com/Roblox/roblox-blender-plugin/releases/latest
