### ISSUE TITLE
Is there a restriction on amount of Material/Textures?

### ISSUE THREAD

**Issue by vini-guerrero** [Roblox/roblox-blender-plugin#34]
When uploading an asset with a single material/texture everything works fine, but for multiple materials/textures I get blank textures (no colors), also using sync option. Manually exporting and uploading thru Roblox Studio textures work fine.

**Comment by Nightriff** [comment]
There are no restrictions, anything that works in studio should theoretically work the same through the API.

To help investigate the discrepancy here, would you please share the .blend file containing the object or collection you're trying to upload with me? If you don't want to share it publicly here, please [send it to me in a direct message on the devforum (@Nightriff)](https://devforum.roblox.com/u/Nightriff/).

**Comment by vini-guerrero** [comment]
I'm currently using this model - 3 materials, 3 textures, (will send private msg with the file), blank blend file, just imported it and tried uploading, upload works, but no textures on the other side (Roblox Studio or Webste).

![image](https://github.com/Roblox/roblox-blender-plugin/assets/18181786/d1ad49a2-8e91-4037-b3ca-3187a150b0ef)

![image](https://github.com/Roblox/roblox-blender-plugin/assets/18181786/33aa0825-7b75-41b6-86cf-69cd413b4ae4)

![image](https://github.com/Roblox/roblox-blender-plugin/assets/18181786/19c1b634-3dc1-4a79-83ed-63e9312cccb5)

**Comment by Nightriff** [comment]
Closing this as stale since I can't reproduce it. If anyone experiences this in the future, we can re-open this.
