### ISSUE TITLE
Plugin incompatible with Blender 4.0 - Upload fails with no errors, AttributeError: 'Context' object has no attribute 'selected_ids'

### ISSUE THREAD

**Issue by NubQugo** [Roblox/roblox-blender-plugin#35]
Maybe I'm doing something wrong? I click the collection I want to import, click N - Upload. Sometimes I'll pick to upload to my personal account, sometimes to our game group. Either way, it takes 10-30 minutes to upload. By then, I'm out of patience and time, so I give up and try again another day, just to still struggle. No errors. Nothing. Just never shows up. Yes, same issue with the latest release. I even change file name, and still have the same issue.

**Comment by NubQugo** [comment]
Updated to Blender 4, and now it's talking about bones?.. I'm thinking this plug in may be too outdated now, since Blender keeps updating so often. Was amazing for the few times I was able to use it. ![Medal_M6uTRTv6VQ](https://github.com/Roblox/roblox-blender-plugin/assets/151858699/0792cdd1-91e8-4803-9d17-19163d614ce1)

**Comment by EngyneMac** [comment]
> Updated to Blender 4, and now it's talking about bones?.. I'm thinking this plug in may be too outdated now, since Blender keeps updating so often. Was amazing for the few times I was able to use it. ![Medal_M6uTRTv6VQ](https://private-user-images.githubusercontent.com/151858699/285274353-0792cdd1-91e8-4803-9d17-19163d614ce1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzk4OTcsIm5iZiI6MTcwMTA3OTU5NywicGF0aCI6Ii8xNTE4NTg2OTkvMjg1Mjc0MzUzLTA3OTJjZGQxLTkxZTgtNDgwMy05ZDE3LTE5MTYzZDYxNGNlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxMDA2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2M5MzNiOWNhNjhmOWI5ZDE4NDIxNDUwMDE1Y2U3YmQ4ZTBjMDhmNTY0OGZlYzY5YTEzYTAzMTI5OTMzNGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZYoILnGyCYCkeajY0yO0GqVfcnlEIeVtyhYURskQgpI)

https://github.com/Roblox/roblox-blender-plugin/issues/32

**Comment by othomson-roblox** [comment]
Can you download the latest release (which fixes the 4.0 issue) and confirm if you are still having problems?

https://github.com/Roblox/roblox-blender-plugin/releases/tag/v1.0.2

**Comment by Nightriff** [comment]
Someone else encountered the same 'No module named `roblox-blender-plugin-1` issue. Let's track that one here: https://github.com/Roblox/roblox-blender-plugin/issues/39
Please add to that issue if you're experiencing that new problem.

Closing this issue since the other issues seem to be resolved by updating the plugin to v1.0.3.
