### ISSUE TITLE
Unknown Error when attempting upload

### ISSUE THREAD

**Issue by pluh01** [Roblox/roblox-blender-plugin#40]
Seems I can't do anything the easy way.

My previous issue with the dependency module was fixed, but now it's failing to upload, giving me an Unknown Error.
Here is what the console writes out when it happens.

![image](https://github.com/Roblox/roblox-blender-plugin/assets/155758274/d5128346-f412-408a-90d0-456a7e031857)

**Comment by Nightriff** [comment]
Thanks for reporting. Can you confirm if this is still happening? We made a change recently on the backend open cloud API that might fix this.

**Comment by pluh01** [comment]
Nope still happening.
Although now it takes a good 10 seconds before it displays Unknown Error.

**Comment by Nightriff** [comment]
Thanks for confirming it's still happening. To investigate further, I want to see if something in the file you're uploading is causing the server to fail. Would you share the .blend file containing the object or collection you're trying to upload with me? You can share it with me in a [direct message on the devforum (@Nightriff)](https://devforum.roblox.com/u/Nightriff/) if you don't want to share it publicly here.

**Comment by Nightriff** [comment]
Closing this as not enough information is provided. Feel free to comment again if you have more information.
