### ISSUE TITLE
Error during login: No module named 'pyjw_key_fetcher', Internal Client Error

### ISSUE THREAD

**Issue by ZarosRiel** [Roblox/roblox-blender-plugin#44]
When trying to login and confirming i get this:

Internal client error.
No module named 'pyjwt_key_fetcher'

**Comment by Nightriff** [comment]
Thanks for reporting. You're not the only one who has experienced this, see related issue https://github.com/Roblox/roblox-blender-plugin/issues/14 .
To resolve this, please try these steps:
1) Uninstall the plugin
2) Restart Blender
3) Reinstall the plugin
4) Disable your antivirus (this is probably blocking the pyjwt_key_fetcher installation)
5) Click the install dependencies button on the plugin
6) After it completes, re-enable your antivirus

Let me know if this fixes the issue for you.

**Comment by Nightriff** [comment]
I'm closing this as duplicate for now. Feel free to re-open if the above instructions don't work for you.
