### ISSUE TITLE
Unable to upload any texture

### ISSUE THREAD

**Issue by NewOpenAi** [Roblox/roblox-blender-plugin#46]
Blender 4.0
AutoUpdate ticked

![螢幕擷取畫面 2024-04-06 134848](https://github.com/Roblox/roblox-blender-plugin/assets/123947870/d76e8c87-e210-4bd3-8215-ee8dcec80797)
![螢幕擷取畫面 2024-04-06 134808](https://github.com/Roblox/roblox-blender-plugin/assets/123947870/f03cc6ab-4994-4257-ba65-1cb4555887bc)
![螢幕擷取畫面 2024-04-06 135144](https://github.com/Roblox/roblox-blender-plugin/assets/123947870/8703262b-5f8d-4905-98cb-9010516a9c11)

**Comment by Nightriff** [comment]
@NewOpenAi Would you be able to provide a file containing a texture that causes this issue for you, so we can try to reproduce this?

**Comment by Nightriff** [comment]
Closing this as stale since I can't reproduce it. If anyone experiences this in the future, we can re-open this.
