### ISSUE TITLE
How to remove object in MyPackage?

### ISSUE THREAD

**Issue by htkindesign** [Roblox/roblox-blender-plugin#49]
Here is capture, I don't know how to remove this. 
![image](https://github.com/Roblox/roblox-blender-plugin/assets/79962981/cf165c39-bbb6-4d4a-b0fe-b12b9d326adb)

**Comment by Nightriff** [comment]
Unfortunately, Roblox doesn't have a way to remove assets as of now. If you have difficulty finding the asset you're looking for, I recommend using the Search box. 

I also recommend making a feature request on the devforum that explains why you need to remove items in your packagess. Doing this will make sure your pain point is known and it can trigger the right chain of events to get a new feature implemented!

In any case, this is a part of Roblox's toolbox feature, not specific to this Blender add-on, so I am closing this comment.
