### ISSUE TITLE
Unable to upload anything

### ISSUE THREAD

**Issue by 1charg** [Roblox/roblox-blender-plugin#51]
Whenever i try to upload anything it just says "Operation Timed Out"
![Capture](https://github.com/Roblox/roblox-blender-plugin/assets/163556434/a82e449d-0add-4e67-bda9-7b81bbf5e70d)

**Comment by Nightriff** [comment]
I see you've closed this issue yourself. If you continue experiencing this in the future, feel free to re-open and we can investigate further.
