### ISSUE TITLE
unable to press AutoUpdate

### ISSUE THREAD

**Issue by hjyuh** [Roblox/roblox-blender-plugin#64]
It isn't letting me press autoupdate, and im wondering if this is a bug, or a mistake on my side.
![image](https://github.com/user-attachments/assets/bba6c675-82ad-4e03-8e72-6ab8d22959de)

**Comment by hjyuh** [comment]
I tried doing it in a different place, and It worked. Seemed to be something on my end.

**Comment by Nightriff** [comment]
Glad you got it working. Feel free to add a comment if anyone figures out what causes this, but I'm closing this now since it's no longer causing you a problem.
