### ISSUE TITLE
Add On Error

### ISSUE THREAD

**Issue by PlasmaShield27** [Roblox/roblox-blender-plugin#66]
I have an error for the Roblox plug in it doesn't work separately or together

![Screenshot 2024-10-15 171825](https://github.com/user-attachments/assets/e8ceb7ac-8f50-4e0e-9907-295964fc0297)

**Comment by PlasmaShield27** [comment]
I noticed one other person had this issue but never elaborated how to fix it

**Comment by Nightriff** [comment]
Looks similar to https://github.com/Roblox/roblox-blender-plugin/issues/57

To help diagnose, can you share the output from the console during the upload attempt?

* On Windows, in Blender go to `Window` > `Toggle System Console` to see the console.
* On Mac OS, you'll need to start Blender from a terminal window.

**Comment by Nightriff** [comment]
For anyone coming across this issue in the future: The answer to this specific problem is here https://github.com/Roblox/roblox-blender-plugin/issues/57#issuecomment-2418261843

And an issue for this bug can be tracked here https://github.com/Roblox/roblox-blender-plugin/issues/67
