### ISSUE TITLE
Can't enable add-on in Blender.

### ISSUE THREAD

**Issue by Hugtrain** [Roblox/roblox-blender-plugin#7]
**_I am very new to GitHub so I'm very sorry if I've posted this in the wrong place. Everything is confusing!!!_**

I installed the program straight from the release page. I went to Blender and selected the Zip file and it installed, but when I went to enable it it gave me this error:
![image](https://github.com/Roblox/roblox-blender-plugin/assets/95592014/596b429d-4787-454e-904d-473b20742697)

Is this my fault or is something else going on here?

Thank you!
Hugo.

**Comment by itsFrank** [comment]
Hi Hugo, welcome to GitHub! This is likely the right place. From the screenshot that you are using Blender version 2.83.

I believe the plugin is only compatible with Blender versions >3.0. I would suggest installing a more recent version of Blender and retrying.

**Comment by Hugtrain** [comment]
Oh, right! I haven't used Blender in a bit. I should probably update it.

Thanks!
